spring:
  application:
    name: UserProduct
  datasource:
    url: jdbc:h2:mem:the-commerce;NON_KEYWORDS=USER
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    database-platform: H2
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        show_sql: true

springdoc:
  use-fqn: true
  api-docs:
    path: /api-docs # API 문서 생성 경로
  swagger-ui:
    path: /swagger-ui.html # Swagger-ui 경로
