spring:
  application:
    name: UserProduct
  datasource:
    url: jdbc:h2:mem:the-commerce
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
